
name: notebook
channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-singleuser
  - tqdm
  - s3fs
  - awscli
  - datalad
  - datalad-container
  - singularity
  - altair
  - seaborn
  - graphviz
  - pygraphviz
  - python-graphviz
  - jax
  - numba
  - dcm2niix
  - openneuro-py
  - nitime
  - statsmodels
  - openneuro-py
  - dask
  - pip
